import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import BranchLink from '@/components/server/BranchLink';
import ScrollTop from '@/components/client/ScrollTop';
import Header from '@/layout/Header';
import Footer from '@/layout/Footer';
import Topbar from '@/layout/Topbar';

import './globals.css';

const roboto = Roboto({
  weight: ['400', '500', '600', '700'],
  subsets: ['vietnamese', 'latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Foso Test',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={roboto.className}>
      <body>
        <div className="cursor-default">
          <Topbar />
          <Header />
          {children}
          <BranchLink />
          <Footer />
          <ScrollTop />
        </div>
      </body>
    </html>
  );
}
